manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joelspadin
      url-base: https://github.com/joelspadin
  projects:
    - name: zmk
      remote: joelspadin
      revision: kscan-read-by-port
      import: app/west.yml
  self:
    path: config
